"""initial

Revision ID: ba7f4e952953
Revises: 
Create Date: 2026-04-04 21:07:27.977615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7f4e952953'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flexibility_commitments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('suggestion_id', sa.String(length=255), nullable=False),
    sa.Column('suggestion_type', sa.String(length=50), nullable=False),
    sa.Column('community_id', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reward_points_estimated', sa.Integer(), nullable=False),
    sa.Column('reward_points_actual', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='flexibility'
    )
    op.create_index(op.f('ix_flexibility_flexibility_commitments_user_id'), 'flexibility_commitments', ['user_id'], unique=False, schema='flexibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flexibility_flexibility_commitments_user_id'), table_name='flexibility_commitments', schema='flexibility')
    op.drop_table('flexibility_commitments', schema='flexibility')
    # ### end Alembic commands ###
